# CMI
#destination: "../cmi-www/_site/t/pwom"

environment: standalone

sourceId: 16
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'Droga Mistrzostwa'
tagline:      'Now, we begin...'
description:  'A pathway of awakening from Jeshua through Jon Marc Hammer (Jayem)'
url:          'https://www.christmind.info/t/pwom'
baseurl:      ''
keywords:     "Christ Mind, Way of Mastery, Jeshua, Jayem, Way of the Heart, Way of Transformation, Way of Knowing"
port:         9916

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
src-url:      'https://www.christmind.info/t/pwom'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-sitemap

#  - jekyll-feed

# Collections for transcripts
collections:
  lj:
    output: true
    title: Listy Jeszuy
  wos:
    output: true
    title: Droga Sługi

defaults:

  - scope:
      path: ""
      type: lj
    values:
      layout: transcript
      book: "Listy Jeszuy"
      publisher: "Droga Mistrzostwa"
      image: "/public/img/wom/tjlN-big.jpg"
      big-separator: "/public/img/wom/big.jpg"
      little-separator: "/public/img/wom/little.jpg"
      image-width: 612
      image-height: 938
      bid: "LJ"
      audio: false

  - scope:
      path: ""
      type: wos
    values:
      layout: transcript
      book: "Droga Sługi"
      publisher: "Droga Mistrzostwa"
      image: "/public/img/wom/wosN-big.jpg"
      big-separator: "/public/img/wom/big.jpg"
      little-separator: "/public/img/wom/little.jpg"
      image-width: 612
      image-height: 938
      bid: "WOS"
      audio: false

exclude: [
  moved.html, deploy, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

