# CMI

environment: integration
destination: "../cmi-www/_site/t/pwom"

sourceId: 16
cmiTitle: "Nauki Umysłu Chrystusa"
siteName: "Biblioteka Nauk Umysłu Chrystusa"

# Setup
title:        'Droga Mistrzostwa'
tagline:      'Now, we begin...'
description:  'Ścieżka przebudzenia dana przez Jeszuę w komunii z Jayemem (Jon Marc Hammer)'
url:          'https://www.christmind.info/t/pwom'
baseurl:      ''
keywords:     "Christ Mind, Way of Mastery, Jeshua, Jayem, Way of the Heart, Way of Transformation, Way of Knowing"
port:         9916

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
src-url:      'https://www.christmind.info/t/pwom'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

# Collections for transcripts
collections:
  notes:
    output: true
  acq:
    output: true
    title: Get Acquainted
  lj:
    output: true
    title: Listy Jeszuy
  wos:
    output: true
    title: Droga Sługi
  woh:
    output: true
    title: Droga Serca
  wot:
    output: true
    title: Droga Przemiany,
  wok:
    output: true
    title: Droga Poznania,
  early:
    output: true
    title: Wczesne lata Drogi,

defaults:

  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/pwom/public/img/wom/acq-big.jpg"
      image-width: 612
      image-height: 792
      bid: "acq"
      audio: false
      pnumToggle: false
  - scope:
      path: ""
      type: lj
    values:
      layout: transcript
      book: "Listy Jeszuy"
      publisher: "Droga Mistrzostwa"
      image: "/t/pwom/public/img/wom/tjl-big.jpg"
      big-separator: "/t/pwom/public/img/wom/big.jpg"
      little-separator: "/t/pwom/public/img/wom/little.jpg"
      image-width: 612
      image-height: 877
      bid: "LJ"
      audio: false

  - scope:
      path: ""
      type: wos
    values:
      layout: transcript
      book: "Droga Sługi"
      publisher: "Droga Mistrzostwa"
      image: "/t/pwom/public/img/wom/wos-big.jpg"
      big-separator: "/t/pwom/public/img/wom/big.jpg"
      little-separator: "/t/pwom/public/img/wom/little.jpg"
      image-width: 612
      image-height: 877
      bid: "WOS"
      audio: false

  - scope:
      path: ""
      type: woh
    values:
      layout: transcript
      book: "Droga Serca"
      publisher: "Droga Mistrzostwa"
      image: "/t/pwom/public/img/wom/wos-big.jpg"
      big-separator: "/t/pwom/public/img/wom/big.jpg"
      image-width: 612
      image-height: 877
      bid: "WOH"
      audio: true

  - scope:
      path: ""
      type: wot
    values:
      layout: transcript
      book: "Droga Przemiany"
      publisher: "Droga Mistrzostwa"
      image: "/t/pwom/public/img/wom/wot-big.jpg"
      big-separator: "/t/pwom/public/img/wom/big.jpg"
      image-width: 612
      image-height: 877
      bid: "WOT"
      audio: true

  - scope:
      path: ""
      type: wok
    values:
      layout: transcript
      book: "Droga Poznania"
      publisher: "Droga Mistrzostwa"
      image: "/t/pwom/public/img/wom/wok-big.jpg"
      big-separator: "/t/pwom/public/img/wom/big.jpg"
      image-width: 612
      image-height: 877
      bid: "WOK"
      audio: true

  - scope:
      path: ""
      type: early
    values:
      layout: transcript
      book: "Wczesne lata Drogi"
      publisher: "Droga Mistrzostwa"
      image: "/t/pwom/public/img/wom/early-big.jpg"
      big-separator: "/t/pwom/public/img/wom/big.jpg"
      image-width: 612
      image-height: 877
      bid: "EARLY"
      audio: false

exclude: [
  bin, standalone, moved.html, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

